# Generated by Django 3.0.7 on 2020-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=255)),
                ('visibilty', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('media', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_name', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('therapy_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('therapist_id', models.AutoField(primary_key=True, serialize=False)),
                ('therapist_name', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
            ],
        ),
    ]
