# Generated by Django 3.0.7 on 2020-06-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auptimism_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeplan',
            name='visibilty',
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=255)),
                ('Mother_name', models.CharField(max_length=255)),
                ('email_father', models.EmailField(max_length=254)),
                ('email_mother', models.EmailField(max_length=254)),
                ('phoneno_father', models.IntegerField()),
                ('phoneno_mother', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('profile_pic', models.FileField(upload_to='')),
                ('Medical_report', models.FileField(upload_to='')),
                ('past_report', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auptimism_main.Therapist')),
            ],
        ),
    ]
