# Generated by Django 3.0.7 on 2020-06-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auptimism_main', '0002_auto_20200620_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('media', models.FileField(upload_to='')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auptimism_main.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=255)),
                ('i_description', models.TextField()),
                ('i_email', models.EmailField(max_length=254)),
                ('i_phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='homeplan',
        ),
    ]
